# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_cg_fpga_0_0/design_2_cg_fpga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_cg_fpga_0_0 || ORIG_REF_NAME==design_2_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_top_0_0/design_2_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_top_0_0 || ORIG_REF_NAME==design_2_top_0_0} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
